# Generated by Django 3.2.13 on 2022-07-06 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participants',
            new_name='participant',
        ),
        migrations.AlterField(
            model_name='klab',
            name='maxSpaces',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='joinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostId', to=settings.AUTH_USER_MODEL)),
                ('klab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klabs.klab')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
