# Generated by Django 3.2.14 on 2022-07-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klabs', '0002_auto_20220706_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='klab',
            name='remainingSpaces',
            field=models.IntegerField(default=3),
        ),
    ]
