# Generated by Django 3.2.13 on 2022-07-09 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klabs', '0004_inviterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klab',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
