# Generated by Django 3.2.14 on 2022-07-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klabs', '0007_auto_20220714_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klab',
            old_name='remainingSpaces',
            new_name='takenSpaces',
        ),
    ]
