# Generated by Django 3.2.13 on 2022-07-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='visibility',
        ),
    ]
